
import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import java.awt.Container;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sujit
 */
public class HomeWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeWindowWindow
     */
    public HomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        goto2 = new javax.swing.JMenu();
        homeMenu = new javax.swing.JMenuItem();
        addMnBtn = new javax.swing.JMenuItem();
        addWordMenu = new javax.swing.JMenuItem();
        showWordsMenu = new javax.swing.JMenuItem();
        startTest = new javax.swing.JMenuItem();
        readMode = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlashCards 1.0");
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 600));

        goto2.setText("Goto");
        goto2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        goto2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                goto2MenuSelected(evt);
            }
        });
        goto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goto2ActionPerformed(evt);
            }
        });

        homeMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeMenu.setText("Home");
        homeMenu.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                homeMenuMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        homeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuActionPerformed(evt);
            }
        });
        goto2.add(homeMenu);

        addMnBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addMnBtn.setText("Simple Add");
        addMnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMnBtnActionPerformed(evt);
            }
        });
        goto2.add(addMnBtn);

        addWordMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addWordMenu.setText("Add words");
        addWordMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordMenuActionPerformed(evt);
            }
        });
        goto2.add(addWordMenu);

        showWordsMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showWordsMenu.setText("Show words");
        showWordsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showWordsMenuActionPerformed(evt);
            }
        });
        goto2.add(showWordsMenu);

        startTest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startTest.setText("Start Test");
        startTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTestActionPerformed(evt);
            }
        });
        goto2.add(startTest);

        readMode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        readMode.setText("Read Mode");
        readMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readModeActionPerformed(evt);
            }
        });
        goto2.add(readMode);

        jMenuBar1.add(goto2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goto2ActionPerformed
            
    }//GEN-LAST:event_goto2ActionPerformed

    private void goto2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_goto2MenuSelected

    }//GEN-LAST:event_goto2MenuSelected

    private void homeMenuMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_homeMenuMenuKeyPressed
        
    }//GEN-LAST:event_homeMenuMenuKeyPressed

    private void homeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuActionPerformed
        HomeWindow nj = new HomeWindow();
         Container nextPane = nj.getContentPane();
         Container activePane = getContentPane();
        System.out.println(nextPane==activePane);
        setContentPane(nextPane);
        System.out.println(nextPane==activePane);
    }//GEN-LAST:event_homeMenuActionPerformed

    private void addWordMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordMenuActionPerformed
        Container contentPane = new AddWords().getContentPane();
        setContentPane(contentPane);
    }//GEN-LAST:event_addWordMenuActionPerformed

    private void showWordsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showWordsMenuActionPerformed
        Container contentPane = new ShowWords().getContentPane();
        setContentPane(contentPane);
    }//GEN-LAST:event_showWordsMenuActionPerformed

    private void readModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readModeActionPerformed
        Container contentPane = new ReadWindow().getContentPane();
        setContentPane(contentPane);
    }//GEN-LAST:event_readModeActionPerformed

    private void startTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTestActionPerformed
        Container contentPane = new TestWindow().getContentPane();
        setContentPane(contentPane);
    }//GEN-LAST:event_startTestActionPerformed

    private void addMnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMnBtnActionPerformed
        Vact v = new Vact();
        v.setVisible(true);
        System.out.println("new Vact raised:"+v.hashCode());
    }//GEN-LAST:event_addMnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            Properties pro = AcrylLookAndFeel.getThemeProperties("Red-Giant-Font");
            AcrylLookAndFeel.setTheme(pro);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMnBtn;
    private javax.swing.JMenuItem addWordMenu;
    private javax.swing.JMenu goto2;
    private javax.swing.JMenuItem homeMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem readMode;
    private javax.swing.JMenuItem showWordsMenu;
    private javax.swing.JMenuItem startTest;
    // End of variables declaration//GEN-END:variables
}
