
import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import note.util.FCUtil;
import java.awt.ItemSelectable;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sujit
 */
public class ShowWords extends javax.swing.JFrame {

    /**
     * Creates new form ShowWords
     */
    public ShowWords() {
        initComponents();
        loadData();
    }
    public void loadData(){
        
        //getDateFromDB method probides dates
        String[] dates = FCUtil.getDatesFromDB();
        
        datesCbx.setModel(new javax.swing.DefaultComboBoxModel<>(dates));
        wordsLst.setListData(FCUtil.getWordsByDate(dates[0]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        wordsLst = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        datesCbx = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        textTa = new javax.swing.JTextArea();
        editBtn = new javax.swing.JButton();
        writeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wordsLst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wordsLst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        wordsLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                wordsLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(wordsLst);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Select Date");

        datesCbx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datesCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        datesCbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                datesCbxItemStateChanged(evt);
            }
        });

        textTa.setColumns(20);
        textTa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTa.setRows(5);
        jScrollPane2.setViewportView(textTa);

        editBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editBtn.setText("Edit");

        writeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        writeBtn.setText("Write Notes");
        writeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(writeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(datesCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(writeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(datesCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int n123 = 0;
    private void wordsLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_wordsLstValueChanged
        
              
    }//GEN-LAST:event_wordsLstValueChanged

    private void loadList(String[] values){
        wordsLst.setListData(values);
    }
    
    private void datesCbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_datesCbxItemStateChanged
        if(evt.getSource() == datesCbx && evt.getStateChange()==1){
            String date = datesCbx.getSelectedItem().toString();
            System.out.println(date);
            String[]  values = FCUtil.getWordsByDate(date);
            wordsLst.setListData(values);
        }
    }//GEN-LAST:event_datesCbxItemStateChanged

    private void writeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeBtnActionPerformed
        String key = wordsLst.getSelectedValue();

        if (key!=null&&!key.equals("null")) {
            AddNotes an = new AddNotes(this, true);
            an.getWordTf().setText(key);
            an.getTextTa().setText(FCUtil.getCmtByWord(key));
            an.setVisible(true);
            an.setTitle("Write Notes.");
            
            String editedValue = an.getTextTa().getText();
            System.out.println(editedValue);
            an.dispose();
            if (FCUtil.updateCmt( key,editedValue)) {
                textTa.setText(editedValue);
                JOptionPane.showMessageDialog(null, "Updated", "Notes has been successfully.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Not Updated", "Value not updated", JOptionPane.ERROR_MESSAGE);
            }
        } else { //Not selected any list
            JOptionPane.showMessageDialog(null, "Please select a word from the list", "Please select", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_writeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try { 
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            Properties pro = AcrylLookAndFeel.getThemeProperties("Red-Giant-Font");
            AcrylLookAndFeel.setTheme(pro);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ShowWords.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowWords().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> datesCbx;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textTa;
    private javax.swing.JList<String> wordsLst;
    private javax.swing.JButton writeBtn;
    // End of variables declaration//GEN-END:variables
}
