
import com.sun.glass.events.KeyEvent;
import note.util.FCUtil;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sujit
 */
public class VacHunt1 extends javax.swing.JFrame {

    /**
     * Creates new form VacHunt
     */
    public VacHunt1() {
        initComponents();
        init();
    }
    private void init(){
        getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTa = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        queTa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add the word");
        setBackground(new java.awt.Color(51, 51, 51));

        textTf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTf.setForeground(new java.awt.Color(255, 255, 153));
        textTf.setToolTipText("Enter the word");
        textTf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textTf.setMargin(new java.awt.Insets(5, 10, 5, 5));

        textTa.setColumns(20);
        textTa.setLineWrap(true);
        textTa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTa.setForeground(new java.awt.Color(255, 255, 255));
        textTa.setTabSize(0);
        textTa.setToolTipText("Enter the notes.");
        textTa.setWrapStyleWord(true);
        textTa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textTa.setMargin(new java.awt.Insets(5, 5, 5, 5));
        textTa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textTaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(textTa);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        queTa.setColumns(20);
        queTa.setLineWrap(true);
        queTa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        queTa.setForeground(new java.awt.Color(255, 255, 255));
        queTa.setTabSize(0);
        queTa.setToolTipText("Enter the releated question");
        queTa.setWrapStyleWord(true);
        queTa.setBorder(null);
        queTa.setMargin(new java.awt.Insets(5, 5, 5, 5));
        queTa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                queTaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(queTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(textTf))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(textTf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        action();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void queTaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queTaKeyPressed
        int key = evt.getKeyCode();
        System.out.println(evt.getKeyCode());
        if (key == KeyEvent.VK_TAB) {
            System.out.println("Hey you just clicked Tab;");
            JTextArea aj = (JTextArea) evt.getComponent();
            aj.transferFocus();
        }
    }//GEN-LAST:event_queTaKeyPressed

    private void textTaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTaKeyPressed
        int key = evt.getKeyCode();
        System.out.println(evt.getKeyCode());
        if (key == KeyEvent.VK_TAB) {
            System.out.println("Hey you just clicked Tab;");
            JTextArea aj = (JTextArea) evt.getComponent();
            aj.transferFocus();
        }
    }//GEN-LAST:event_textTaKeyPressed

    private void clear(){
        textTf.setText("");
        queTa.setText("");
        textTa.setText("");
        transferFocus();
        
    }
    
    private void action(){
        String word = textTf.getText().trim();
        String question = queTa.getText().trim();
        String notes = textTa.getText().trim();
        boolean isAdded = false;
        
        if(!word.equals("")&&(!question.equals("")||!notes.equals(""))){
            isAdded = FCUtil.insertWordAndNotes(word, question, notes);
            clear();
            System.out.println("Word is added.");
        }else{
            JOptionPane.showMessageDialog(this, "Enter Added", "Please enter data", JOptionPane.ERROR_MESSAGE);
            clear();
        }
                
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VacHunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VacHunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VacHunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VacHunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VacHunt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea queTa;
    private javax.swing.JTextArea textTa;
    private javax.swing.JTextField textTf;
    // End of variables declaration//GEN-END:variables
}
