
import com.jtattoo.plaf.noire.NoireLookAndFeel;
import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sujit
 */
public class ViewMode extends javax.swing.JFrame {

    /**
     * Creates new form AddWord
     */
    public ViewMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topicTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        briefTa = new javax.swing.JTextArea();
        image = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesTa = new javax.swing.JTextArea();
        titleTf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        saveBtn = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        viewTopicMBtn = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        imageCk = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        includeMBtn = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Mode");

        topicTf.setEditable(false);
        topicTf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topicTf.setText("Topic");
        topicTf.setFocusable(false);
        topicTf.setMargin(new java.awt.Insets(5, 5, 5, 5));

        briefTa.setColumns(20);
        briefTa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        briefTa.setRows(5);
        briefTa.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(briefTa);

        image.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        notesTa.setColumns(20);
        notesTa.setRows(5);
        jScrollPane2.setViewportView(notesTa);

        titleTf.setEditable(false);
        titleTf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleTf.setText("Title");
        titleTf.setFocusable(false);
        titleTf.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jButton2.setText("Next");

        jButton3.setText("Prev");

        jButton1.setText("Update");

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setMnemonic('N');
        jMenuItem7.setText("New");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setMnemonic('O');
        jMenuItem4.setText("Open");
        jMenuItem4.setToolTipText("Opens all the words.");
        jMenu1.add(jMenuItem4);

        saveBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveBtn.setMnemonic('S');
        saveBtn.setText("Save");
        saveBtn.setToolTipText("Save the word to the data base.");
        jMenu1.add(saveBtn);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setMnemonic('x');
        jMenuItem5.setText("Exit");
        jMenuItem5.setToolTipText("");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");
        jMenu2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu2ItemStateChanged(evt);
            }
        });

        viewTopicMBtn.setSelected(true);
        viewTopicMBtn.setText("Topics");
        viewTopicMBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                viewTopicMBtnItemStateChanged(evt);
            }
        });
        jMenu2.add(viewTopicMBtn);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Brief");
        jCheckBoxMenuItem1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem1ItemStateChanged(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Notes");
        jCheckBoxMenuItem2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem2ItemStateChanged(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        imageCk.setSelected(true);
        imageCk.setText("Image");
        imageCk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                imageCkItemStateChanged(evt);
            }
        });
        imageCk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageCkActionPerformed(evt);
            }
        });
        jMenu2.add(imageCk);

        jMenuItem6.setText("Todays work");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('I');
        jMenu3.setText("Insert");

        includeMBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        includeMBtn.setSelected(true);
        includeMBtn.setText("Update Image");
        includeMBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                includeMBtnItemStateChanged(evt);
            }
        });
        includeMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                includeMBtnActionPerformed(evt);
            }
        });
        jMenu3.add(includeMBtn);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Display");

        jMenuItem1.setText("Night Owl");
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Early Bird");
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(topicTf)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(titleTf))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topicTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void includeMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_includeMBtnActionPerformed
        System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_includeMBtnActionPerformed

    private void includeMBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_includeMBtnItemStateChanged
       
            
        
    }//GEN-LAST:event_includeMBtnItemStateChanged

    private void jMenu2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu2ItemStateChanged
        
    }//GEN-LAST:event_jMenu2ItemStateChanged

    public static final JScrollPane getScrollPane(JComponent component) {
        Container p = component.getParent();
        if (p instanceof JViewport) {
            Container gp = p.getParent();
            if (gp instanceof JScrollPane) {
                return (JScrollPane) gp;
            }
        }
        return null;

    } 
    
    
    private void viewTopicMBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_viewTopicMBtnItemStateChanged
        int state = evt.getStateChange(); // 1 is Selected, 2 is Unselected.
        if (state == 1) {
            topicTf.setVisible(true);
            revalidate();
            repaint();
        } else {
            topicTf.setVisible(false);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_viewTopicMBtnItemStateChanged

    private void jCheckBoxMenuItem1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ItemStateChanged
        int state = evt.getStateChange(); // 1 is Selected, 2 is Unselected.
        JScrollPane scrollPane = getScrollPane(briefTa);
        if (state == 1) {
            scrollPane.setVisible(true);
            briefTa.setVisible(true);
            revalidate();
            repaint();
            
        } else {
            briefTa.setVisible(false);
            scrollPane.setVisible(false);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ItemStateChanged

    private void jCheckBoxMenuItem2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ItemStateChanged
        int state = evt.getStateChange(); // 1 is Selected, 2 is Unselected.
        JScrollPane scrollPane = getScrollPane(notesTa);
        if (state == 1) {
            scrollPane.setVisible(true);
            notesTa.setVisible(true);
            revalidate();
            repaint();
        } else {
            scrollPane.setVisible(false);
            notesTa.setVisible(false);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_jCheckBoxMenuItem2ItemStateChanged

    private void imageCkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageCkActionPerformed
    
    }//GEN-LAST:event_imageCkActionPerformed

    private void imageCkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_imageCkItemStateChanged
        int state = evt.getStateChange(); // 1 is Selected, 2 is Unselected.;
        if (state == 1) {
            image.setVisible(true);
        } else {
            image.setVisible(false);
        }
    }//GEN-LAST:event_imageCkItemStateChanged

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        AddWord ad = new AddWord();
        ad.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            NoireLookAndFeel.setTheme("Large-Font");
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
            
            
            /* Create and display the form */   
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ViewMode().setVisible(true);
                    System.out.println(NoireLookAndFeel.getTheme().getName());
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddWord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AddWord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AddWord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddWord.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea briefTa;
    private javax.swing.JLabel image;
    private javax.swing.JCheckBoxMenuItem imageCk;
    private javax.swing.JCheckBoxMenuItem includeMBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea notesTa;
    private javax.swing.JMenuItem saveBtn;
    private javax.swing.JTextField titleTf;
    private javax.swing.JTextField topicTf;
    private javax.swing.JCheckBoxMenuItem viewTopicMBtn;
    // End of variables declaration//GEN-END:variables
}
